#spring.data.mongodb.uri=mongodb+srv://***REMOVED***@tecnophone.qozfyul.mongodb.net/?retryWrites=true&w=majority&appName=Tecnophone
#BD en Usa
spring.data.mongodb.uri=mongodb+srv://***REMOVED***@cluster0.evulhgc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
server.port=${PORT:8080}
server.address=0.0.0.0
spring.data.mongodb.database=DB-Tecnophones

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true