spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}
server.port=${PORT:8080}
server.address=0.0.0.0
server.forward-headers-strategy=framework
server.error.include-message=always
spring.data.mongodb.database=${MONGO_DB_NAME:DB-Tecnophones}
afrelay.base-url=${AFRELAY_BASE_URL:http://localhost:8000}
afrelay.bearer-token=${AFRELAY_BEARER_TOKEN:1234}

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
